### ISSUE TITLE
Documentation or source code for MAT example

### ISSUE THREAD

**Issue by SBRK** [FlorisSteenkamp/MAT#1]
A documentation or source code for the MAT demo would be great. It is exacly what I am looking for but with the given documentation, I am a bit clueless as to how to get a medial axis transform

**Comment by FlorisSteenkamp** [comment]
Hi SBRK

Yes, it would be hard to extract the MAT without documentation. You would need to dig into the demo source, etc.

I will cook up some proper documentation over the next few days so it can be more useful.

**Comment by FlorisSteenkamp** [comment]
Ok, I have now added docs and some demo code to the repo.

Closing for now, but please let me know should anything still be unclear or if you have any questions or suggestions I would be glad to help.

Please use version 0.1.6 or above as I've updated the code to fix some installation and other issues.
