### ISSUE TITLE
I want to run the code on VS or other C++ based IDEs， how could I do?

### ISSUE THREAD

**Issue by chunfengDou** [FlorisSteenkamp/MAT#20]
I want to run the code on VS or other C++ based IDEs， how could I do?

**Comment by FlorisSteenkamp** [comment]
Hi chunfengDou. 

I use VS Code for my IDE and do not have much experience with Visual Studio.

That said, it should be quite straightforward but unfortunately I would not be able to help you. I suggest you follow some online courses.

Good luck!
