### ISSUE TITLE
does the script works with SVG - letters Z,V,H

### ISSUE THREAD

**Issue by hariharan382** [FlorisSteenkamp/MAT#27]
Sir I am try to imlement   with my svg script which has Z,V,H in it will it work that way?
is your script is based on cuibic or quadratic bezier?

**Comment by FlorisSteenkamp** [comment]
Hi Hari.

Yes, V, H will work.

The library is based on lines (linear polynomial bezier curves),
quadratic polynomial bezier curves AND/OR cubic polynomial bezier
curves.

**Comment by hariharan382** [comment]
I am having svg , where can I paste or import in webpage based flomat?

**Comment by hariharan382** [comment]
Where shpu;d i add the svg file sir , or should i have to just copy the path ? for finding MAT

**Comment by hariharan382** [comment]
Sir you said to run node index.js but where can I add the svg file
