### ISSUE TITLE
compile error due to non-ascii character

### ISSUE THREAD

**Issue by Goodhao** [FlorisSteenkamp/MAT#32]
I am new to typescript.
When I tried to use `tsc index.ts` to compile your code, I got errors like this:

> node_modules/flo-bezier3/node/implicit-form/exact/get-implicit-form1-.d.ts:7:5 - error TS1131: Property or signature expected.
> 
> 7     vₓ: number;
>       ~

Maybe it is caused by non-ascii character in your code?
How can I fix it?

**Comment by hariharan382** [comment]
Do you any have idea on how this algorithm works?, If yes please can you help me out
