### ISSUE TITLE
Consulting Arrangement?

### ISSUE THREAD

**Issue by vonotype** [FlorisSteenkamp/MAT#38]
Hi Floris,

Sorry for opening an issue, but I can't find your email address or other contact info in any of your repos. I was wondering if you'd be interested in making some modifications to your MAT/SAT library for us. We're open to both hourly and project based work. I think it would be relatively short/easy (at least for you, not me 🤣) , but I'd love to also get your feedback on what we're doing with it and the modifications could increase in scope if that was something you'd be interested in. It's obviously very niche and highly specialized.

If you could shoot me an email, that'd be fantastic, even if you aren't interested so I know to stop pursuing it. 

I've ROT13 encoded my email to make it less likely I get spam: wba.ibatvyyrea(ng)zbabglcr.pbz, my personal email address is wibatvyyrea(ng)tznvy.pbz in case there are any delivery issues. 

The library is fantastic, and has been incredibly helpful, thank you for making it open source!

**Comment by FlorisSteenkamp** [comment]
I've sent you an email. Let me know if you didn't get it then I'll try the other one. 👍🏼
