### ISSUE TITLE
Polygons with holes

### ISSUE THREAD

**Issue by junpingcao** [FlorisSteenkamp/MAT#5]
The lib works great in most scenarios. But I find it fails to detect mats in some polygons with holes. Pls check following two samples.

**The first one with 5 holes CANNOT be detected correctly. Actually the number of mats is zero.**

_M 2568 -576 L 2568 -1083 L 2881 -1083 L 2881 -1216 L 2568 -1216 L 2568 -1661 L 1923 -1661 L 1923 -1984 L 2832 -1984 L 2832 -2116 L 2122 -2116 C 2218 -2232 2325 -2377 2411 -2513 L 2261 -2574 C 2184 -2439 2052 -2245 1947 -2116 L 1038 -2116 L 1145 -2180 C 1078 -2290 930 -2458 801 -2574 L 678 -2510 C 798 -2390 940 -2229 1007 -2116 L 242 -2116 L 242 -1984 L 1127 -1984 L 1127 -1661 L 439 -1661 L 439 -1536 L 1127 -1536 L 1127 -1216 L 193 -1216 L 193 -1083 L 1127 -1083 L 1127 -701 L 414 -701 L 414 -576 L 1044 -576 C 820 -298 451 -37 135 92 C 168 120 211 171 236 209 C 540 73 894 -188 1127 -472 L 1127 272 L 1268 272 L 1268 -576 L 1781 -576 L 1781 272 L 1923 272 L 1923 -494 C 2175 -217 2546 51 2847 190 C 2872 152 2915 102 2946 73 C 2636 -50 2255 -311 2012 -576 L 2568 -576 
M 1268 -701 L 1268 -1083 L 1781 -1083 L 1781 -701 L 1268 -701 
M 1268 -1536 L 1781 -1536 L 1781 -1216 L 1268 -1216 L 1268 -1536 
M 1268 -1984 L 1781 -1984 L 1781 -1661 L 1268 -1661 L 1268 -1984 
M 2427 -1536 L 2427 -1216 L 1923 -1216 L 1923 -1536 L 2427 -1536 
M 2427 -701 L 1923 -701 L 1923 -1083 L 2427 -1083 L 2427 -701_

**The second one also with 5 holes CAN be detected without problem.** 

_M 2718 -1090 L 2912 -1090 L 2912 -1216 L 2718 -1216 L 2718 -1661 L 2230 -1661 L 2230 -1920 L 2860 -1920 L 2860 -2049 L 2239 -2049 C 2334 -2179 2442 -2347 2528 -2491 L 2390 -2557 C 2316 -2408 2187 -2192 2086 -2049 L 1136 -2049 L 1136 -1920 L 1585 -1920 L 1585 -1661 L 1182 -1661 L 1182 -1536 L 1585 -1536 L 1585 -1216 L 1093 -1216 L 1093 -1090 L 1585 -1090 L 1585 -768 L 1167 -768 L 1167 -642 L 1529 -642 C 1391 -352 1164 -66 949 80 C 980 105 1026 155 1050 189 C 1241 43 1443 -215 1585 -489 L 1585 270 L 1720 270 L 1720 -642 L 2095 -642 L 2095 267 L 2230 267 L 2230 -505 C 2390 -237 2614 27 2808 174 C 2832 136 2875 90 2909 62 C 2691 -78 2442 -365 2285 -642 L 2718 -642 L 2718 -1090 
M 2230 -768 L 2230 -1090 L 2589 -1090 L 2589 -768 L 2230 -768 
M 1720 -768 L 1720 -1090 L 2095 -1090 L 2095 -768 L 1720 -768 
M 1720 -1536 L 2095 -1536 L 2095 -1216 L 1720 -1216 L 1720 -1536 
M 1720 -1920 L 2095 -1920 L 2095 -1661 L 1720 -1661 L 1720 -1920 
M 2589 -1536 L 2589 -1216 L 2230 -1216 L 2230 -1536 L 2589 -1536_

I did some investigation and found there is something wrong in findAndAdd2ProngsOnAllPaths. 
find_and_add_2_prongs_1.findAndAdd2Prongs is failed to return a valid cpNode on last loop.

**Comment by FlorisSteenkamp** [comment]
Hi Ping. Thanks for the bug report 👍.

I have checked the above two cases with the newest code on GitHub and with the version I have locally (not yet on GitHub) and it is working on my side so something must have been fixed in the meantime - haven't looked into it too much yet (down with a bit of a flu :( at the moment).

I wasn't planning on a version bump for about a month (which would also fix all special cases during boolean operations of complex shapes) but if you need the code now I can do a minor version update for you in the meantime?

By the way, thanks for tracing the bug that far - it is actually _very_ hard if you are not completely familiar with the code.

![letter](https://user-images.githubusercontent.com/10459546/76381140-e2ddc500-6311-11ea-82aa-d05ef7189cdb.png)

**Comment by junpingcao** [comment]
Hi Floris,

I have found it works again if I put the inner contours in a specific order. The order of inner contours does matter. 

This is a temporary workaround for me until there is a new update.

Thanks for your reply and take care.

**Comment by FlorisSteenkamp** [comment]
Hi Ping.

Ok, I have the new version on Github now.

The bug turned out to be quite silly.

Enjoy!

PS: Let me know if I missed something and it persists.

**Comment by junpingcao** [comment]
Hi Floris,

New version works great. Thanks for the update.

<img width="378" alt="zi" src="https://user-images.githubusercontent.com/736151/81490518-c4665c80-92b5-11ea-829b-d976beb0d89a.png">

**Comment by FlorisSteenkamp** [comment]
Good to hear. Don't know what you're doing, but it looks complicated :)  Good luck with your project!

**Comment by msurguy** [comment]
@junpingcao I'm building a CNC Text editor tool and it would be great to convert some of the existing fonts into single-stroke fonts to be easily engrave-able or plottable with plotter. You can see the tool here: https://msurguy.github.io/cnc-text-tool/ 
Are you working on a tool to convert text characters into SVG?

**Comment by junpingcao** [comment]
I'm making a tool to compose Chinese character with components. MAT helps me convert Chinese character glyph into graph structures. The structures would be classified into radicals and components. Finally, these components would be re-organized into new Chinese character. 

BTW, your site might also need an update of new MAT. @msurguy
